apiVersion: v1
kind: Service
metadata:
  name: couchdb2-replica
spec:
  type: LoadBalancer
  selector:
    app: couchdb2-replica-node
  ports:
    - port: 5984
      name: couchdb
---
apiVersion: v1
kind: Service
metadata:
  name: couchdb2-replica-admin
spec:
  selector:
    app: couchdb2-replica-node
  ports:
    - port: 5984
      name: couchdb
    - port: 5986
      name: backdoor
  clusterIP: None
